### ISSUE TITLE
Enhancement of developer code needs

### ISSUE THREAD

**Issue by rodrigopex** [zeta-middleware/zeta#28]
Warning to the developer which functions he/she needs to implement. Maybe creating some template file or mocks that are disabled by some definition.

### Template generated on the zeta project folder:

```c
#ifndef ZETA_CORE_SERVICE
void CORE_service_callback(...) {
#warning This function must be implemented. 
}

void CORE_task() {
#warning This function must be implemented.
}
#endif
```

### User code related to CORE service:

```c
ZT_SERVICE_INIT(ZETA_CORE_SERVICE);
void CORE_service_callback(...) {
...
}

void CORE_task() {
...
}
```
The macro would define the ZETA_CORE_SERVICE internally disabling the template code.

**Comment by lucaspeixotot** [comment]
#46 solve this issue indirectly.
