### ISSUE TITLE
Create the Zeta forwarder

### ISSUE THREAD

**Issue by rodrigopex** [zeta-middleware/zeta#37]
This issue has the goal to implement a thread responsible for forwarding messages through the LOG port. The messages can have two directions, from Zeta to ZetaCLI and from ZetaCLI to Zeta. The messages that are sent from Zeta to ZetaCLI carry information about the communication between services and channels in Zeta. The messages that are sent from ZetaCLI to Zeta will be defined in the future.

ISC event definition:
- Prefix = "@ZT_ISC:"
- Payload: A binary Packet encrypted with cbor and base64
- Sufix = \n

The Packet would be:
- Packet ID: int
- Service ID: int
- Channel ID: int
- Operation: int
  - Read = 0
  - Publish = 1
  - Callback triggered = 2
  - Saved on flash = 3
- Message: uint8_t (Byte-array)

**Comment by lucaspeixotot** [comment]
This issue has the goal to implement a thread responsible for forwarding messages through a serial port. The messages can have two directions, from Zeta to ZetaCLI and from ZetaCLI to Zeta. The messages that are sent from Zeta to ZetaCLI carry information about the communication between services and channels in Zeta. The messages that are sent from ZetaCLI to Zeta will be defined in the future.
